<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>Barbecue Guaranteed</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="shortcut icon" href="../favicon.png">
  <link rel="shortcut icon" href="../favicon.ico">
</head>
<body>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Barbecue Guaranteed</a>
      </div>
      <?php if(!empty($_SESSION['user'])): ?>
        <div class="navbar-right">
          <a class="btn btn-default navbar-btn" href="/dashboard">Dashboard</a>
          <a class="btn btn-default navbar-btn" href="/register-company">Register company</a>
          <a class="btn btn-default navbar-btn" href="/new-order">New order</a>
          <a class="btn btn-default navbar-btn" href="/my-account">My account</a>
          <a class="btn btn-default navbar-btn" href="/logout">Logout</a>
        </div>
      <?php endif; ?>
    </div>
  </nav>
  <div class="container">
