<?php require_once('_header.phtml');?>

<?php pr($_SESSION);?>
<div class="jumbotron">
   <h2 class="text-center">Dashboard</h2>
   <h3 class="text-left">My companies</h3>
   <table class="table table-hover">
      <thead>
         <tr>
            <th>Fantasy name</th>
            <th>CNPJ</th>
            <th>Order amount</th>
         </tr>
      </thead>
      <tbody>
         <tr>
            <td>Druptec Soluções</td>
            <td>28.354.669/0001-09</td>
            <td><a href="">2</a></td>
         </tr>
      </tbody>
   </table>
</div>
<?php require_once('_footer.phtml');?>
