<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Slim 3</title>
  <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
</head>
<body>
  <h1>testing heroku</h1>

  say hello to <a href="/you">you</a>

  <?php if (isset($name)) : ?>
    <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
  <?php else: ?>
    <p>Try <a href="http://www.slimframework.com">SlimFramework</a>
    <?php endif; ?>
  </body>
  </html>
