<?php require_once('_header_unlogged.phtml');?>
<div class="jumbotron col-sm-6 col-sm-offset-3">
  <h2 class="text-center">Login</h2>
  <form class="form-horizontal" name="loginForm" method="post" action="/login">
    <div class="form-group">
      <label for="email" class="col-sm-4 control-label">Email</label>
      <div class="col-sm-8">
        <input type="email" class="form-control" id="email" name="email" placeholder="Your email">
      </div>
    </div>
    <div class="form-group">
      <label for="password" class="col-sm-4 control-label">Password</label>
      <div class="col-sm-8">
        <input type="password" class="form-control" id="password" name="password" placeholder="Type your password">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-4 col-sm-8">
        <a href="/new-account" class="btn btn-warning">Register new account</a>
        <button type="submit" class="btn btn-primary">Login</button>
      </div>
    </div>
  </form>
</div>
<?php require_once('_footer.phtml');?>
