<?php require_once('_header_unlogged.phtml');?>
<div class="jumbotron col-sm-6 col-sm-offset-3">
  <h2 class="text-center">Register new account</h2>
  <form class="form-horizontal" name="accountForm" method="post" action="/new-account">
    <div class="form-group">
      <label for="email" class="col-sm-4 control-label">Email</label>
      <div class="col-sm-8">
        <input type="email" class="form-control" id="email" name="email" placeholder="Your email" required>
      </div>
    </div>
    <div class="form-group">
      <label for="password" class="col-sm-4 control-label">Password</label>
      <div class="col-sm-8">
        <input type="password" class="form-control" id="password" name="password" placeholder="Type your password" required>
      </div>
    </div>
    <div class="form-group">
      <label for="repeat-password" class="col-sm-4 control-label">Repeat password</label>
      <div class="col-sm-8">
        <input type="password" class="form-control" id="repeat-password" name="repeat-password" placeholder="Retype your password" required>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-4 col-sm-8">
        <a href="/login" class="btn btn-success">I have an account</a>
        <button type="submit" class="btn btn-primary">Register</button>
      </div>
    </div>
  </form>
</div>
<?php require_once('_footer.phtml');?>
