<?php require_once('_header.phtml');?>
<div class="jumbotron">
  <h2 class="text-center">Register new order</h2>
  <hr/>
  <form class="form-horizontal" name="orderForm" method="post" action="/new-order">
    <div class="form-group">
      <label for="company" class="col-sm-2 control-label">Select company</label>
      <div class="col-sm-2">
        <select class="input-sm" id="company" name="company">
          <option value="">Select a company</option>
          <?php foreach ($companies as $key => $company): ?>
            <option value="<?=$company->cnpj;?>"><?=$company->name;?></option>
          <?php endforeach; ?>
        </select>
      </div>
    </div>
    <div class="form-group">
      <label for="product" class="col-sm-2 control-label">Select product</label>
      <div class="col-sm-2">
        <select class="input-sm" id="product">
          <option value="">Select product</option>
          <option value="Cerveja">Cerveja</option>
          <option value="Carne">Carne</option>
          <option value="Pão de alho">Pão de alho</option>
          <option value="Refrigerante">Refrigerante</option>
          <option value="Guardanapo">Guardanapo</option>
          <option value="Carvão">Carvão</option>
          <option value="Alcool">Alcool</option>
          <option value="Churrasqueira">Churrasqueira</option>
        </select>
      </div>
      <div class="col-sm-2">
        <input type="number" class="form-control" id="amount" placeholder="Amount">
      </div>
      <div class="col-sm-2">
        <button id="addProduct" class="btn btn-success">Add product</button>
      </div>
    </div>
    <br/>
    <input type="hidden" name="products" />
    <table id="list" class="table table-hover table-bordered">
      <thead>
        <tr>
          <th>Product</th>
          <th>Amount</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        
      </tbody>
    </table>
    <div class="form-group">
      <div class="col-sm-offset-4 col-sm-4">
        <button type="submit" class="btn btn-primary btn-block">Close order</button>
      </div>
    </div>
  </form>
</div>
<?php require_once('_footer.phtml');?>
<?php require_once('__script.phtml');?>
