<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>Barbecue Guaranteed</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Barbecue Guaranteed</a>
      </div>
    </div>
  </nav>

  new-account

  <nav class="navbar navbar-inverse navbar-fixed-bottom">
    <div class="container">
      <p class="navbar-text navbar-right">Make by <a href="http://chroda.com.br/" target="_blank" class="navbar-link">chroda</a></p>
    </div>
  </nav>
</body>
</html>
