<?php require_once('_header.phtml');?>
<div class="jumbotron">
  <h2 class="text-center">Register company</h2>
  <form class="form-horizontal" name="companyForm" method="post" action="/register-company">
    <div class="form-group">
      <label for="name-fantasy" class="col-sm-2 control-label">Name fantasy</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="name-fantasy" placeholder="Name fantasy of company">
      </div>
    </div>
    <div class="form-group">
      <label for="cnpj" class="col-sm-2 control-label">CNPJ</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="cnpj" placeholder="CNPJ">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Register</button>
      </div>
    </div>
  </form>
</div>
<?php require_once('_footer.phtml');?>
